cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('decrement/<int:product_id>', views.cart_decrement, name='cart_decrement'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove')
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

retro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=164, db_index=True)
    slug = models.SlugField(max_length=164, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('core:product_list_by_category', kwargs={'category_slug': self.slug})


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=164, db_index=True)
    slug = models.SlugField(max_length=164, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True, null=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('core:product_detail', kwargs={'id': self.id, 'slug': self.slug})
    

cart/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from core.models import Product

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product, quantity=1)
    return redirect(f"{request.META.get('HTTP_REFERER', '/')}?cart_open=1")

@require_POST
def cart_decrement(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.decrement(product=product)
    return redirect(f"{request.META.get('HTTP_REFERER', '/')}?cart_open=1")

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product)
    return redirect(f"{request.META.get('HTTP_REFERER', '/')}?cart_open=1")

core/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

def product_list(request, category_slug=None):
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    search_query = request.GET.get('search_query','').strip()

    category = None
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    if search_query:
        products = products.filter(name__icontains=search_query)
        category = None

    sort_option = request.GET.get('sort', '')
    if sort_option:
        products = apply_sort(products, sort_option)

    return render(request, 'core/product/list.html',
                  {'products': products,
                   'category': category,
                   'categories': categories,
                   'search_query': search_query,
    })

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    related_products = Product.objects.filter(category=product.category).exclude(id=product.id)[:4]

    return render(request, 'core/product/detail.html',
                  {'product': product,
                   'related_products': related_products,
    })

def apply_sort(products, sort_option):
    if sort_option == 'price_asc':
        return products.order_by('price')
    elif sort_option == 'price_desc':
        return products.order_by('-price')
    elif sort_option == 'name_asc':
        return products.order_by('name')
    elif sort_option == 'name_desc':
        return products.order_by('-name')
    return products

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Arcanum{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">

    {% load static %}
</head>
<body>
    <nav class="navbar navbar-expand-lg" style="background-color: #ebebebff;">
        <div class="container d-flex justify-content-center align-items-center">

            <a class="navbar-brand" href="{% url 'core:product_list' %}">
                <img src="{% static 'core/images/logo.png' %}" alt="Logo" width="50" height="50">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'product_list' %}active fw-bold{% endif %}" aria-current="page"
                            href="{% url 'core:product_list' %}">
                            Home
                        </a>
                    </li>
                    
                    {% for c in categories %}
                        <li class="nav-item">
                            <a class="nav-link {% if c and c.slug == category.slug %}active fw-bold{% endif %}"
                                href="{{ c.get_absolute_url }}">
                                {{ c.name }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
                <div class="d-flex align-items-center">
                    <form class="d-flex me-3" role="search" method="get" action="{% url 'core:product_list' %}">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_query" value="{{ search_query }}"/>
                        <button class="btn btn-dark" type="submit">Find</button>
                    </form>
                    <button type="button" class="btn btn-light position-relative" data-bs-toggle="modal" data-bs-target="#cartModal">
                        <i class="bi bi-cart"></i>
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-dark">
                            {{ cart|length }}
                        </span>
                    </button>
                </div>   
            </div>
        </div>
    </nav>

    <div class="container mt-4 mb-5">
        {% block content %}{% endblock content %}
    </div>

    <footer class="bg-dark text-white py-4 mt-5">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h5>RETRO</h5>
                    <p>The best retro shop</p>
                </div>
                <div class="col-md-4">
                    <h5>contacts</h5>
                    <p>Email: retroitem@gmail.com<br>phone: +380956568639</p>
                </div>
                <div class="col-md-4">
                    <h5>We in socials</h5>
                    <a href="#" class="text-white me-2"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="text-white me-2"><i class="bi bi-instagram"></i></a>
                    <a href="#" class="text-white me-2"><i class="bi bi-telegram"></i></a>
                    <a href="#" class="text-white"><i class="bi bi-vk"></i></a>
                </div>
            </div>
        </div>
    </footer>

    <!-- Modal -->
    <div class="modal fade" id="cartModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <!-- Header -->
                <div class="modal-header">
                    <h5 class="modal-title">Cart</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <!-- Body -->
                <div class="modal-body">
                    <ul class="list-group">
                        {% for item in cart %}
                            <li class="list-group-item d-flex align-items-center justify-content-between">
                                <div class="d-flex align-items-center">
                                    <a href="{{ item.product.get_absolute_url }}">
                                        <img src="{{ item.product.image.url }}"
                                            class="img-fluid rounded me-3" 
                                            style="width: 100%; object-fit: contain; max-height: 50px;"
                                            alt="{{ item.product.name }}">
                                    </a>
                                    <a href="{{ item.product.get_absolute_url }}" class="text-decoration-none text-dark">
                                        {{ item.product.name }}
                                    </a>
                                </div>

                                <div class="d-flex align-items-center">
                                    <form action="{% url 'cart:cart_decrement' item.product.id %}" method="post" class="d-inline me-1 d-flex align-items-center">
                                        {% csrf_token %}
                                        {% if item.quantity == 1 %}
                                            <button type="submit" class="btn btn-sm text-dark disabled" style="background: transparent; border: none; padding: 0; width: 25px; height: 25px; text-align: center;">
                                                <strong>-</strong>
                                            </button>
                                        {% else %}
                                            <button type="submit" class="btn btn-sm text-dark" style="background: transparent; border: none; padding: 0; width: 25px; height: 25px; text-align: center;">
                                                <strong>-</strong>
                                            </button>
                                        {% endif %}
                                    </form>

                                    <span class="mx-2 px-2 py-1 border rounded text-center d-flex justify-content-center align-items-center" style="display:inline-block; width:30px;">
                                        {{ item.quantity }}
                                    </span>

                                    <form action="{% url 'cart:cart_add' item.product.id %}" method="post" class="d-inline ms-1 d-flex align-items-center">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-sm text-dark" style="background: transparent; border: none; padding: 0; width: 25px; height: 25px; text-align: center;">
                                            <strong>+</strong>
                                        </button>
                                    </form>

                                    <span class="mx-2 text-end text-nowrap" style="display:inline-block; width:80px; height:25px;">
                                        {{ item.total_price }}$
                                    </span>
                                    <form action="{% url 'cart:cart_remove' item.product.id %}" method="post" style="display:inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                    </form>
                                </div>
                            </li>
                        {% empty %}
                            <li class="list-group-item list-group-item-secondary">Empty</li>
                        {% endfor %}
                    </ul>
                </div>

                <!-- Footer -->
                <div class="modal-footer">
                    <strong>Total: {{ cart.get_total_price }}$</strong>
                    <button type="button" class="btn btn-dark" disabled>Make an order</button>
                </div>

            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>


    <script>
        window.addEventListener('pageshow', function(event) {
            if (event.persisted) {
                window.location.reload();
            }
        });
        const param = new URLSearchParams(window.location.search)
        if (param.get('cart_open') === '1') {
            new bootstrap.Modal(document.getElementById('cartModal')).show();

            param.delete('cart_open');
            const newUrl = window.location.pathname + (param.toString() ? '?' + param.toString() : '');
            window.history.replaceState({}, document.title, newUrl);
        }
    </script>
</body>
</html>

core/templates/core/product/detail.html
{% extends "core/base.html" %}

{% block content %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ product.image.url }}" class="img-fluid rounded border border-1"alt="{{ product.name }}">
        </div>

        <div class="col-md-6 d-flex flex-column">
            <h2 class="mb-3">{{ product.name }}</h2>
            <p class="text-muted">{{ product.description }}</p>
            
            <h4 class="text my-3"><strong>{{ product.price }} $</strong></h4>

            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Add to cart</button>
            </form> 
            
            <div class="mt-4">
                <p><strong>Category:</strong>
                    <a href="{{ product.category.get_absolute_url }}" class="text-dark">{{ product.category.name }}</a>
                </p>
                <p><strong>Availability:</strong> {% if product.available %}In stock{% else %}Out of stock{% endif %}</p>
            </div>
        </div>
    </div>

    {% if related_products %}
        <div class="related-products mt-5">
            <h2>Simular products</h2>
            <div class="row">
                {% for product in related_products %}
                    <div class="col-md-3 mb-4">
                        <div class="card h-100">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-dark"> {{ product.name }}</a>
                                </h5>
                                <p class="card-text">{{ product.price }} $</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
</div>
{% endblock content %}

core/templates/core/product/list.html
{% extends "core/base.html" %}

{% block content %}

<div class="d-flex justify-content-between align-items-center">
    {% if search_query %}
        <h3>Search results for "{{ search_query }}"</h3>
    {% else %}
            <h3>{% if category %}{{ category.name }}{% else %}All items{% endif %}</h3>
    {% endif %}

    <ul class="nav">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <strong>Sort by</strong>
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="?{% if search_query %}search_query={{ search_query }}&{% endif %}sort=price_asc">Price: Low to High</a></li>
                <li><a class="dropdown-item" href="?{% if search_query %}search_query={{ search_query }}&{% endif %}sort=price_desc">Price: High to Low</a></li>
                <li><a class="dropdown-item" href="?{% if search_query %}search_query={{ search_query }}&{% endif %}sort=name_asc">Name: A to Z</a></li>
                <li><a class="dropdown-item" href="?{% if search_query %}search_query={{ search_query }}&{% endif %}sort=name_desc">Name: Z to A</a></li>
            </ul>
        </li>
    </ul>
</div>

<div class="row row-cols-1 row-cols-md-4 g-3">
    {% for product in products %}
    <div class="col">
        <div class="card h-100">
            <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" 
                    class="card-img-top" 
                    alt="{{ product.name }}"
                    style="width: 100%; object-fit: contain; max-height: 310px;">
            </a>
            <div class="card-body d-flex flex-column">
                <h5 class="card-title">
                    <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-dark">{{ product.name }}</a>
                </h5>
                        
                <p class ="card-text">{{ product.price }} $</p>

                <a href="{{ product.get_absolute_url }}" class="btn btn-outline-dark w-100 mt-auto">View Details</a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="alert alert-secondary" role="alert">
        No products found.
    </div>
    {% endfor %}
</div>
{% endblock content %}